brain_two/urls.py
from django.contrib import admin
from django.urls import include, path
from todos.views import your_signup_view
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("todos/", include("todos.urls")),
    path("admin/", admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', your_signup_view, name='signup'),
]

todos/urls.py
from django.urls import path
from todos.views import (
    todo_list,
    todo_items,
    todo_list_detail,
    todo_list_create,
    todo_list_update,
    your_signup_view,
    your_login_view,
    your_logout_view,
)


app_name = "todos"

urlpatterns = [
    path("", todo_list, name="todo_list_list"),
    path("<int:id>/", todo_list_detail, name="todo_list_detail"),
    path("create/", todo_list_create, name="todo_list_create"),
    path("<int:todo_list_id>/items/", todo_items, name="todo_items"),
    path("<int:id>/edit/", todo_list_update, name="todo_list_update"),
    path('signup/', your_signup_view, name='signup'),
    path('login/', your_login_view, name='login'),
    path('logout/', your_logout_view, name='logout'),
]

todos/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class TodoItem(models.Model):
    task = models.CharField(max_length=200)
    due_date = models.DateTimeField(blank=True, null=True)
    completed = models.DateTimeField(null=True, blank=True)
    list = models.ForeignKey(
        TodoList, on_delete=models.CASCADE, related_name="items"
    )


def is_completed(self):
    return self.completed is not None


is_completed.boolean = True

todos/forms.py
from django import forms
from .models import TodoList


class TodoListForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ["name"]
        widgets = {"name": forms.TextInput(attrs={"class": "form-control"})}

todos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from todos.models import TodoList
from todos.forms import TodoListForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout

@login_required
def todo_list(request):
    todo_lists = TodoList.objects.all()
    context = {"todo_lists": todo_lists}
    return render(request, "todos/list.html", context)

@login_required
def todo_items(request, todo_list_id):
    todo_list = get_object_or_404(TodoList, id=todo_list_id)
    todo_items = todo_list.items.all()
    return render(
        request,
        "todos/todo_items.html",
        {"todo_list": todo_list, "todo_items": todo_items},
    )

@login_required
def todo_list_detail(request, id):
    todo_list = get_object_or_404(TodoList, id=id)
    todo_items = todo_list.items.all()
    context = {"todo_list": todo_list, "todo_items": todo_items}
    return render(request, "todos/detail.html", context)

@login_required
def todo_list_create(request):
    if request.method == "POST":
        form = TodoListForm(request.POST)
        if form.is_valid():
            todo_list = form.save()
            return redirect("todo_list_detail", id=todo_list.id)
    else:
        form = TodoListForm()
    return render(request, "todos/create.html", {"form": form})

@login_required
def todo_list_update(request, id):
    todo_list = get_object_or_404(TodoList, id=id)
    if request.method == "POST":
        form = TodoListForm(request.POST, instance=todo_list)
        if form.is_valid():
            form.save()
            return redirect("todo_list_detail", id=todo_list.id)
    else:
        form = TodoListForm(instance=todo_list)
    return render(
        request, "todos/update.html", {"form": form, "todo_list": todo_list}
    )

def your_signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)  # Log the user in after signup
            return redirect('todos:todo_list_list')  # Redirect to a page after signup
    else:
        form = UserCreationForm()
    return render(request, 'todos/signup.html', {'form': form})

def your_login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('todos:todo_list_list')  # Redirect to a page after login
    else:
        form = AuthenticationForm()
    return render(request, 'todos/login.html', {'form': form})

@login_required
def your_logout_view(request):
    logout(request)
    return render(request, 'todos/logout.html')

todos/templates/todos/base.html
<!-- todos/templates/todos/base.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}My App{% endblock %}</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding-top: 60px;
            background-color: #7a5b45;
            color: #000000;
        }

        header {
            background-color: #000000;
            padding: 10px 0;
            color: white;
            text-align: center;
        }

        nav {
            background-color: #212529;
            padding: 10px 0;
            text-align: center;
            /* Center the links */
        }

        nav a {
            display: inline-block;
            /* Make links display in a line */
            color: #e2d2b0;
            margin: 0 15px;
            /* Add margin to create space between links */
            text-decoration: none;
        }

        .container {
            margin-top: 20px;
            background-color: #e2d2b0;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            color: #7a5b45;
        }

        a {
            color: #000000;
        }

        table {
            width: 100%;
            margin-top: 20px;
            border-collapse: collapse;
        }

        th,
        td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #dee2e6;
        }

        th {
            background-color: #000000;
            color: #e2d2b0;
        }
    </style>
    {% block extra_styles %}{% endblock %}
</head>

<body>
    <header>
        <h1>My Todo App</h1>
        {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'todos:logout' %}">Logout</a>
        {% else %}
        <a class="btn btn-primary" href="{% url 'todos:signup' %}">Sign Up</a>
        <a class="btn btn-primary" href="{% url 'todos:login' %}">Login</a>
        {% endif %}
    </header>

    <nav>
        <a href="{% url 'todos:todo_list_list' %}">My Lists</a>
        <a href="{% url 'todos:todo_list_create' %}">Create a new list</a>
        {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a href="{% url 'login' %}">Login</a>
        {% endif %}
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    {% block extra_scripts %}{% endblock %}
</body>

</html>

todos/templates/todos/create.html
{% extends 'todos/base.html' %}

{% block title %}My Lists{% endblock %}

{% block content %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Create a new List</title>
</head>

<body>
    <h1>Create a new List</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
</body>

</html>
{% endblock %}

todos/templates/todos/detail.html
{% extends 'todos/base.html' %}

{% block title %}My Lists{% endblock %}

{% load static %}

<!DOCTYPE html>
<html>
{% block content %}
<main>
    <div>
        <h1>{{ todo_list.name }}</h1>
        <p><a href="{% url 'todos:todo_list_update' id=todo_list.id %}">Edit</a></p>
        <h2>Tasks</h2>
        <table>
            <thead>
                <tr>
                    <th>Task</th>
                    <th>Due date</th>
                </tr>
            </thead>
            <tbody>
                {% for task in todo_items %}
                <tr>
                    <td><a href="{% url 'todos:todo_list_update' id=task.id %}">{{ task.task }}</a></td>
                    <td>{{ task.due_date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock %}

</html>

todos/templates/todos/list.html
{% extends 'todos/base.html' %}

{% block title %}My Lists{% endblock %}

{% block content %}
<main class="container mt-5">
    <div class="row">
        <div class="col-md-8">
            <h1>My Lists</h1>
            <a class="btn btn-primary" href="{% url 'todos:todo_list_create' %}">Create a new list</a>
            <table class="table mt-3">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of items</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for todo_list in todo_lists %}
                    <tr>
                        <td><a href="{% url 'todos:todo_list_detail' todo_list.id %}">{{ todo_list.name }}</a></td>
                        <td>{{ todo_list.items.count }}</td>
                        <td>
                            <a class="btn btn-warning btn-sm"
                                href="{% url 'todos:todo_list_update' todo_list.id %}">Edit</a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="2">No todo lists found.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</main>
{% endblock %}

todos/templates/todos/logout.html
{% extends 'base.html' %}

{% block title %}Log Out{% endblock %}

{% block content %}
<h2>Logged Out Successfully</h2>
<p>Thank you for using our application. You have been successfully logged out.</p>
{% endblock %}

todos/templates/todos/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h2>Sign Up</h2>
<form method="post" action="{% url 'todos:signup' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
</form>
{% endblock %}

todos/templates/todos/update.html
{% extends 'todos/base.html' %}

{% block title %}My Lists{% endblock %}

{% block content %}
<main>
    <h1>Edit Todo List</h1>
    <div>
        <p><a href="{% url 'todos:todo_list_update' id=todo_list.id %}">Edit</a></p>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save changes</button>
    </form>
</main>
{% endblock %}